config/routes.rb
EasyURL::Application.routes.draw do
  resources :links
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :boxes

  controller :links do
    get '/preview/:id' =>:preview ,as: :preview
    get 'addbox/:id' => :choose_box, as: :addtobox
    post 'addbox/:id' => :add_to_box, as: :addtobox
  end

  root to: "static_pages#home"
  match '/home', to:'static_pages#home'
  match '/bookmark', to:'static_pages#bookmark'

  match '/signup', to:'users#new'
  match '/signin', to:'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/create', to: 'links#create'
  match '/*tails', to: 'links#redirect', :requirements => { :tails => /.*/ }
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@link = Link.new
  	if signed_in?
  		@links=current_user.links.paginate(page: params[:page], per_page: 10)
  		@boxes=current_user.boxes.paginate(page: params[:page], per_page: 10)
  	end
  end

  def bookmarktool
  	
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_boxes.html.erb
<h1 class="page-header">Your boxes <small>(<%= @boxes.count %>)</small></h1>
<%= link_to "Create new box", new_box_path, remote:true, class: "btn btn-inverse add-btn" %>
<% @boxes.each do |box| %> 
<%= render box %>
<% end %>
<%= will_paginate @boxes%>

app/views/static_pages/_links.html.erb
<h1 class="page-header">Your links <small>(<%= @links.count %>)</small></h1>
<% @links.each do |link| %> 
<%= render link %>
<% end %>
<%= will_paginate @links%>

app/views/static_pages/_popup.html.erb
<div class="modal hide fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>

app/views/static_pages/_userpage.html.erb
<%= image_tag "http://placehold.it/940x150" %>
<hr>
<%= form_for @link,:html => { :class => "form form-inline" } do |f| %>
	<%= render 'shared/error_messages', object: @link %>
	<input id="link_rlink" name="link[rlink]" class="span6" placeholder="Enter your looooooooong url" type="text"> in box
	<%= select("link", "box_id", Box.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'}, {:class => "span4"})%>
	<%= f.submit "Shorten it!!!", class: "btn btn-primary" %>
	<small><br><a id="custom">customize your URL?</a></small>
	<div id="custom-field" style="display:none">
		<%= get_base_url %>
	<input id="link_name" name="link[name]" class="span4"></div>
<% end %>
<div class="navbar">
			<div class="navbar-inner">
				<ul class="nav nav-pills" id="myTab">
					<li class="active"><a id="links" data-toggle="tab"><i class="icon-star-empty"></i> Links </a></li>
					<li><a id="boxes" data-toggle="tab"><i class="icon-inbox"></i> Boxes</a></li>
				</ul>
			</div>
		</div>
<div class="row">	
	<div class="span8">
		<div class="tab-content">
		<div class="tab-pane active" id="content">		
			<%= render 'links' %>
		</div>
		</div>
	</div>

	<div class="span4">
		<%= image_tag "http://placehold.it/300x450" %>
		<hr>
		<%= image_tag "http://placehold.it/300x200" %>
		<hr>
		<%= image_tag "http://placehold.it/300x700" %>
	</div>
</div>


<script type="text/javascript">
	function displayDetails(id){
		$("#d-content"+id).show("fast");
	}

	function closeDetails(id){
		$("#d-content"+id).hide("fast");
	}
	$('#links').click(function(){
		$('#content').html("<%=j render 'links' %> ")
	})

	$('#boxes').click(function(){
		$('#content').html("<%=j render 'boxes' %> ")
	})
</script>

app/views/static_pages/_welcome.html.erb
<div class="hero-unit">
<h1>Welcome to EasyURL</h1>
	<%= form_for(@link) do |f| %>
	<%= render 'shared/error_messages', object: @link %>
	<input id="link_rlink" name="link[rlink]" class="span6" placeholder="Enter your looooooooong url" type="text">
	<br>
	<%= f.submit "Shorten it!!!", class: "btn btn-primary btn-large" %>
	<small>or <a id="custom">customize your URL?</a></small>
	<div id="custom-field" style="display:none">
		<%= get_base_url %>
	<input id="link_name" name="link[name]" class="span4"></div>
	<%end%>
	You can <%= link_to "sign in", signin_path %> or <%= link_to "register", signup_path %> to get more services
</div>

app/views/static_pages/bookmark.html.erb
<% provide(:title,"Bookmark Tool") %>
<div class="bookmark">
	<h1>Drag this icon below to Bookmarks bar</h1>
<a href="javascript:void(location.href='http://localhost:3000/create?link%5Brlink%5D='+encodeURIComponent(location.href))" onmouseover="window.status='';return true" onclick="return false"><%= image_tag 'icon.png', :alt => "EasyURL", class: "icon" %></a>
	<h5>Then push it when you think your URL is too long</h5>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if signed_in? %>
<%= render 'userpage' %>
<% else %>
<%= render 'welcome' %>
<% end %>

<script type="text/javascript">
	$('#custom').click(function(){
		$("#custom-field").show("fast");
	})
</script>

app/views/static_pages/notfound.html.erb
<% provide(:title,"Not found") %>
<div style="text-align: center">
<%= image_tag '404.png' %>
<h1>This URL has not been used</h1>
<h4>Do you want to use this url?</h4>
<%= render 'shared/form'%>
</div>