config/routes.rb
EasyURL::Application.routes.draw do
  resources :links
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :boxes

  controller :links do
    get '/preview/:id' =>:preview ,as: :preview
    get 'addbox/:id' => :choose_box, as: :addtobox
    post 'addbox/:id' => :add_to_box, as: :addtobox
  end

  root to: "static_pages#home"
  match '/home', to:'static_pages#home'
  match '/bookmark', to:'static_pages#bookmark'

  match '/signup', to:'users#new'
  match '/signin', to:'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/create', to: 'links#create'
  match '/*tails', to: 'links#redirect', :requirements => { :tails => /.*/ }
  

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :name, :user_id
  has_many :links
  belongs_to :user

  validates :name, presence: true, length: { maximum: 100 }

  default_scope order: 'boxes.created_at DESC'

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
	before_filter :correct_user ,only: [:show, :destroy, :edit, :update]
	before_filter :signed_in_user

	def new
		@box=Box.new
		respond_to do |format|
			format.js
			format.html
		end
	end

	def show
		@box=Box.find(params[:id])
		@links=@box.links.paginate(page: params[:page], per_page: 10)
	end

	def create
		@box=current_user.boxes.build(params[:box])
		if @box.save
			flash[:success] = "Create new box succesfully"
			redirect_to root_path
		else
			flash.now[:error] = "Error orrcured"
			render 'new'
		end
	end

	def destroy
    	@box.destroy
    	redirect_to root_path
  	end

  	def edit
  		@box=current_user.boxes.find(params[:id])
  		respond_to do |format|
  			format.js
  		end
  	end

  	def update
  		@box=current_user.boxes.find(params[:id])
  		if @box.update_attributes(params[:box])
  			flash[:success] = "Box name changed"
  			redirect_to @box
  		else 
  			flash[:error] = "Some error occured, please try again"
  			redirect_to @box
  		end
  	end


private
	def correct_user
      @box = current_user.boxes.find_by_id(params[:id])
      redirect_to root_url if @box.nil?
  	end

  	def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
  	end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_box.html.erb
<div class="well item-link">
<%= link_to box.name, box, class: "title"%>  <span class="label label-important pull-right"><%= box.links.count %> links</span>
<div class="btn-group toolbar">
	<%= link_to 'Rename' , edit_box_path(box), remote: true, class: "btn btn-small" %>
	<%= link_to 'Delete' , box, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-small" %>
</div><div class="date pull-right">Created <%= time_ago_in_words(box.created_at)%> ago</div>
<div id="b-content<%=box.id %>" class="details" style="display: none">
</div>
</div>

app/views/boxes/_edit.html.erb
<%= form_for(@box) do |f| %>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Rename box</h3>
  </div>
  <div class="modal-body">
      <%= f.label :name, "Enter box name" %>
      <%= f.text_field :name %>
  </div>

  <div class="modal-footer">
    <%= f.submit "Create", class: "btn btn-primary" %>
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/boxes/_link.html.erb
<tr class="item-link">
	<td>
	<a class="title" href="<%= link.rlink %>"> <%=get_favicon(link)%> <%= truncate(link.title, length: 70) %></a><br>
	<input type="text" value="<%= get_base_url+link.name%>" class="span4"/> <span class="label label-success">Easy URL</span>
	<%=link_to '×', link, method: :delete, data: {confirm: "Are you sure"}, class: "close" %>
	<br>
	<%=link_to 'See preview', preview_path(link), class: "box-name" %>
	<td>
</tr>

app/views/boxes/_new.html.erb
<%= form_for(@box) do |f| %>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create new box</h3>
  </div>
  <div class="modal-body">
      <%= f.label :name, "Enter box name" %>
      <%= f.text_field :name %>
  </div>

  <div class="modal-footer">
    <%= f.submit "Create", class: "btn btn-primary" %>
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/boxes/edit.js.erb
$('#contentPopup').addClass('modal').html("<%=j render 'edit' %>").modal('show');

app/views/boxes/new.html.erb
<% provide(:title, 'Create box') %>
<h1 class="big-title">Create box</h1>
<div class="row signup">
  <div class="span6 offset3">
    <%= form_for(@box) do |f| %>
      <%= render 'shared/error_messages', object: @box %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create box", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boxes/new.js.erb
$('#contentPopup').addClass('modal').html("<%=j render 'new' %>").modal('show');

app/views/boxes/show.html.erb
<% provide(:title, "Box: "+@box.name) %>
<div class="row">
	<div class="span4">
		<div class="page-header"><h1><%=@box.name%><h1><small><%= pluralize(@box.links.count, "link") %></small></div>
		<%= link_to 'Rename' , edit_box_path(@box), remote: true, class: "btn btn-large btn-primary" %>
		<%= link_to 'Delete' , @box, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-large btn-primary" %>
	</div>
	<div class="span8">
		<% if @box.links.empty? %>
			<div class="alert alert-info">This box is currently empty</div>
		<%else%>
		<table class="table table-hover table-striped" style="border-left: 1px solid #ccc">
			<% @links.each do |link| %>
				<%= render 'link', link: link %>
			<% end %>
		</table>
		<%= will_paginate @links%>
		<% end %>
	</div>
		
</div>