config/routes.rb
EasyURL::Application.routes.draw do
  resources :links
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :boxes

  controller :links do
    get '/preview/:id' =>:preview ,as: :preview
    get 'addbox/:id' => :choose_box, as: :addtobox
    post 'addbox/:id' => :add_to_box, as: :addtobox
  end

  root to: "static_pages#home"
  match '/home', to:'static_pages#home'
  match '/bookmark', to:'static_pages#bookmark'

  match '/signup', to:'users#new'
  match '/signin', to:'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/create', to: 'links#create'
  match '/*tails', to: 'links#redirect', :requirements => { :tails => /.*/ }
  

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :rlink, :title, :name, :user_id, :desc, :favicon, :box_id
  belongs_to :user
  belongs_to :box

  VALID_NAME_REGEX = /^[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*$/

  validates :rlink, presence: true, length: { maximum: 500}
  validates :name, presence: true, length: {maximum: 81, minimum: 3}, uniqueness: {case_sensitive: true},
  				   format: {with: VALID_NAME_REGEX}

  default_scope order: 'links.created_at DESC'

end
# == Schema Information
#
# Table name: links
#
#  id         :integer         not null, primary key
#  title      :string(255)
#  rlink      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :correct_user, only: [:destroy, :edit, :update]

  def new
  	@link = Link.new
  end

  def create
    #generate random string
    if(params[:link][:name].nil?||params[:link][:name]=="")
      params[:link][:name]=get_url(5) 
    end
    if check_forbidden_name(params[:link][:name])
      flash[:error] =" Your URL has already been used"
      redirect_to root_path
    else
    #get url information
    doc = Pismo::Document.new(params[:link][:rlink])
    if doc.title.nil?
      flash[:error] = "Sorry! Your URL does not seem right"
      redirect_to root_path
    else      
      params[:link][:title]=doc.title
      params[:link][:desc]=doc.description
      params[:link][:favicon]=doc.favicon
      if(signed_in?)
        @link = current_user.links.build(params[:link])
      else      
  	    @link = Link.new(params[:link])      
      end
  	  if(@link.save)
        flash[:success] = "Created shorten url, please copy and store your URL below"
  		  redirect_to preview_path(@link)
  	  else
        flash[:error] = " Error occured! Please check your URL "
  		  redirect_to root_path
      end
    end
  end
  end

  def edit
    @link=Link.find(params[:id])
  respond_to do |format|
      format.js
    end
  end

  def update
    @link=Link.find(params[:id])
    if @link.update_attributes(params[:link])
      flash[:success] = "Updated link successful"
      redirect_to root_path
    else 
      flash[:error] = "Some error occured, please try again"
      redirect_to root_path
    end
  end

  def show
    @link = Link.find(params[:id]);
    @doc = Pismo::Document.new(@link.rlink)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @link.destroy
    flash[:success] = "Link deleted"
    redirect_to root_path
  end


  def preview
    @link = Link.find(params[:id]);
  end

  def choose_box
    @boxes = current_user.boxes.all
    respond_to do |format|
      format.js
    end
  end

  def add_to_box
    @link = Link.find(params[:id]);
    if @link.update_attribute("box_id", params[:box_id])
      flash[:success] = "Add to box"
      redirect_to root_path
    end
  end

  def redirect
    tails=params[:tails]
    name = tails.split('/').first    
    link= Link.find_by_name(name)
    if link.nil?
      @link=Link.new
      render 'static_pages/notfound'
    else
      if link.rlink.last.==('/')
        tails=tails.sub(name+'/','')
      else
        tails=tails.sub(name,'')
      end
      if params[:format].nil?
        redirect_to link.rlink+tails
      else
        redirect_to link.rlink+tails+'.'+params[:format]
      end
    end 
  end

  private

  def get_url(length)
    begin
    gen_url=random_string(length)
    end while !Link.find_by_name(gen_url).nil? # avoid generating the same name
    gen_url
  end

  def random_string(length)
    chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    string = ''
    length.times { string << chars[rand(chars.size)] }
    string
  end

  def correct_user
      @link = current_user.links.find_by_id(params[:id])
      redirect_to root_url if @link.nil?
  end
  
  def check_forbidden_name(name)
    fnames=["home","bookmark","signup","signin","signout","create","addbox"]
    fnames.each do |fname|
      if fname.equal?(name)
        return true
      end
    end
    return false
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_choose_box.html.erb
<%= form_tag addtobox_path do |f| %>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add link to box</h3>
  </div>
  <div class="modal-body">
    Choose box: 
  	<%= select_tag "box_id", options_from_collection_for_select(current_user.boxes.all, "id", "name") %><br>
    or <%= link_to "Create new box", new_box_path,  remote: true %>    
  </div>

  <div class="modal-footer">
    <%= submit_tag "Add to box", class: "btn btn-primary" %>
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/links/_details.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">URL Details</h3>
  </div>
  <div class="modal-body">
  	<h4 class="url-info"><%=get_favicon(@link)%><%= @link.title %></h4>
    <p><%= strip_tags(@link.desc) %></p>
  </div>
  <div class="modal-footer">
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>

app/views/links/_edit.html.erb
<%= form_for(@link) do |f| %>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Edit link</h3>
  </div>
  <div class="modal-body">

      <%= render 'shared/error_messages', object: @link %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :desc %>
      <%= f.text_field :desc %>

      <%= f.label :rlink %>
      <%= f.text_field :rlink %>     

  </div>
  <div class="modal-footer">
    <%= f.submit "Save changes", class: "btn btn-primary" %>
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="well item-link">
<a class="title" href="<%= link.rlink %>"> <%=get_favicon(link)%> <%= link.title %></a><br>
<input type="text" class="span4"value="<%= get_base_url+link.name %>"/>
<span class="label label-success">Easy URL</span>
<div class="date">Created <%= time_ago_in_words(link.created_at)%> ago</div>
<% unless link.box.nil? %>
<div class="box-name" >in <%= link_to link.box.name, link.box %></div>
<% end%>
<div class="btn-group toolbar pull-right" style="display:inline">
	<a class="btn btn-small btn-primary" id="details" onclick="displayDetails(<%=link.id%>)">Details</a>
	<%= link_to 'Edit' , edit_link_path(link), remote: true, class: "btn btn-small btn-primary" %>
	<%= link_to 'Add to box' , addtobox_path(link), remote: true, class: "btn btn-small btn-primary" %>
	<%= link_to 'Delete' , link, method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-small btn-primary" %>
</div>
<div id="d-content<%=link.id %>" class="details" style="display: none">
	<hr>
	<div class="desc"> <%= strip_tags(link.desc)%> </div>	
	<input type="text" class="span4" value="<%= link.rlink %>"/> <span class="label label-important">Real URL</span>
	<a class="close pull-right" onclick="closeDetails(<%=link.id%>)">×</a>
</div>
</div>

app/views/links/choose_box.js.erb
$('#contentPopup').addClass('modal').html("<%=j render 'choose_box' %>").modal('show');

app/views/links/edit.js.erb
$('#contentPopup').addClass('modal').html("<%=j render 'edit' %>").modal('show');

app/views/links/new.html.erb
<h1>Links#new</h1>
<p>Find me in app/views/links/new.html.erb</p>

app/views/links/preview.html.erb
<% provide(:title,"URL Preview") %>
<h1 class="big-title">URL Preview</h1>
<div class="span8 offset2 clearfix">
	Your shorten URL<input class="span8"type="text" value="<%='http://localhost:3000/'+@link.name%>"/>
	Your real URL<input class="span8"type="text" value="<%=@link.rlink%>"/>
	<div class="url-info well">
		<div class="title">
			<% if !@link.favicon.nil? %>
			<%=image_tag @link.favicon %>
			<%end%>
			<%= @link.title %>
		</div>
		<div class="desc"><%= strip_tags(@link.desc) %> </div>
	</div>
</div>

app/views/links/show.html.erb
<% provide(:title,"URL Preview") %>
<h1 class="big-title">URL Preview</h1>
<div class="span8 offset2 clearfix">
	Your shorten URL<input class="span8"type="text" value="<%='http://localhost:3000/'+@link.name%>"/>
	Your real URL<input class="span8"type="text" value="<%=@link.rlink%>"/>
	<div class="url-info well">
		<div class="title">
			<% if !@doc.favicon.nil? %>
			<%=image_tag @doc.favicon %>
			<%end%>
			<%= @doc.title %>
		</div>
		<div class="desc"><%= strip_tags(@doc.description) %> </div>
	</div>
</div>

app/views/links/show.js.erb
$('#contentPopup').addClass('modal').html("<%=j render 'details' %>").modal('show');