config/routes.rb
EasyURL::Application.routes.draw do
  resources :links
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :boxes

  controller :links do
    get '/preview/:id' =>:preview ,as: :preview
    get 'addbox/:id' => :choose_box, as: :addtobox
    post 'addbox/:id' => :add_to_box, as: :addtobox
  end

  root to: "static_pages#home"
  match '/home', to:'static_pages#home'
  match '/bookmark', to:'static_pages#bookmark'

  match '/signup', to:'users#new'
  match '/signin', to:'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/create', to: 'links#create'
  match '/*tails', to: 'links#redirect', :requirements => { :tails => /.*/ }
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Easy URL</a>
    by QuyenLQ
  </small>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="<%=root_path %>" id="logo">EasyURL</a>
      <nav>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>          
          <% if signed_in? %>
          <li><%= link_to "My Profile", current_user %></li>        
          <li class="divider-vertical"></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <li class="divider-vertical"></li>
          <li><%= link_to "Sign up", signup_path %></a></li>
          <% end %>
          <li class="divider-vertical"></li>
          <li><%= link_to "Bookmark Tool", bookmark_path %></li>
          <li class="divider-vertical"></li>
        </ul>
        <nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | EasyURL - Simplify your looooooooooooong URL </title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %> 
</head>
<body>
	<%= render 'layouts/header' %>	
	<div class="container">
		<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

  <div id="contentPopup">    
  </div>
</body>
</html>